In [28]:
import pandas
import time, datetime
import numpy as np
from pandas import DataFrame
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.cross_validation import KFold
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler
from IPython.display import display
from sklearn.preprocessing import scale
from sklearn.linear_model import LogisticRegression

In [29]:
features = pandas.read_csv('/home/ubuntu/Desktop/Coursera ML/week7/final project/features.csv')
features = features.iloc[:, 2:]

display(features.head(5))

,lobby_type,r1_hero,r1_level,r1_xp,r1_gold,r1_lh,r1_kills,r1_deaths,r1_items,r2_hero,r2_level,r2_xp,r2_gold,r2_lh,r2_kills,r2_deaths,r2_items,r3_hero,r3_level,r3_xp,
0,7,11,5,2098,1489,20,0,0,7,67,3,842,991,10,0,0,4,29,5,1909,...
1,0,42,4,1188,1033,9,0,1,12,49,4,1596,993,10,0,1,7,67,4,1506,...
2,7,33,4,1319,1270,22,0,0,12,98,3,1314,775,6,0,0,6,20,3,1297,...
3,1,29,4,1779,1056,14,0,0,5,30,2,539,539,1,0,0,6,75,5,2037,...
4,7,13,4,1431,1090,8,1,0,8,27,2,629,552,0,0,1,7,30,3,884,...

In [30]:
NA_features = {'Features': [], 'NAs, %': []}
filled_values = dict(features.count())
for feature in filled_values.keys():
    if filled_values[feature] != len(features):
        NA_features['Features'].append(feature)
        NA_features['NAs, %'].append((len(features) - filled_values[feature]) / float(len(features)))
NA_features = DataFrame(NA_features)

display(NA_features)

                       Features    NAs, %
0              dire_bottle_time  0.166029
1       radiant_first_ward_time  0.018883
2   radiant_flying_courier_time  0.282619
3              first_blood_time  0.201100
4             dire_courier_time  0.006953
5              first_blood_team  0.201100
6      dire_flying_courier_time  0.268415
7          dire_first_ward_time  0.018780
8           first_blood_player1  0.201100
9           first_blood_player2  0.452402
10          radiant_bottle_time  0.161380
11         radiant_courier_time  0.007117

[12 rows x 2 columns]

In [31]:
print min(features['dire_courier_time'] / float(60))
print max(features['dire_courier_time'] / float(60))

-1.5
4.93333333333

In [32]:
features.fillna(value=999,inplace=True)

In [33]:
cols_del = ['duration',
            'radiant_win',
            'tower_status_radiant',
            'tower_status_dire',
            'barracks_status_radiant', 
            'barracks_status_dire']
data = features.drop(cols_del, axis=1)
labels = features['radiant_win']

In [34]:
display(data.head(5))

data = data.astype(float)
for cols in list(data.columns.values):
    data[cols] = scale(data[cols], copy=False)

display(data.head(5))

,lobby_type,r1_hero,r1_level,r1_xp,r1_gold,r1_lh,r1_kills,r1_deaths,r1_items,r2_hero,r2_level,r2_xp,r2_gold,r2_lh,r2_kills,r2_deaths,r2_items,r3_hero,r3_level,r3_xp,
0,7,11,5,2098,1489,20,0,0,7,67,3,842,991,10,0,0,4,29,5,1909,...
1,0,42,4,1188,1033,9,0,1,12,49,4,1596,993,10,0,1,7,67,4,1506,...
2,7,33,4,1319,1270,22,0,0,12,98,3,1314,775,6,0,0,6,20,3,1297,...
3,1,29,4,1779,1056,14,0,0,5,30,2,539,539,1,0,0,6,75,5,2037,...
4,7,13,4,1431,1090,8,1,0,8,27,2,629,552,0,0,1,7,30,3,884,...

,lobby_type,r1_hero,r1_level,r1_xp,r1_gold,r1_lh,r1_kills,r1_deaths,r1_items,r2_hero,r2_level,r2_xp,r2_gold,r2_lh,r2_kills,r2_deaths,r2_items,r3_hero,r3_level,r3_xp,
0,1.540688,-1.244228,1.400808,1.525972,0.734957,0.969743,-0.537757,-0.578083,-0.509023,0.453467,-0.332256,-0.625222,-0.255162,-0.052580,-0.533149,-0.582396,-1.756715,-0.728192,1.50723,1.308568,...
1,-0.927798,-0.292258,0.501314,-0.080139,-0.247570,-0.246859,-0.537757,1.017574,1.492930,-0.097431,0.578881,0.732454,-0.250795,-0.052580,-0.533149,1.019572,-0.524101,0.438857,0.59158,0.582307,...
2,1.540688,-0.568637,0.501314,0.151070,0.263085,1.190944,-0.537757,-0.578083,1.492930,1.402237,-0.332256,0.224676,-0.726779,-0.498410,-0.533149,-0.582396,-0.934972,-1.004599,-0.32407,0.205660,...
3,-0.575157,-0.691471,0.501314,0.962950,-0.198013,0.306142,-0.537757,-0.578083,-1.309804,-0.678935,-1.243393,-1.170813,-1.242065,-1.055698,-0.533149,-0.582396,-0.934972,0.684551,1.50723,1.539241,...
4,1.540688,-1.182811,0.501314,0.348745,-0.124754,-0.357459,0.968527,-0.578083,-0.108632,-0.770751,-1.243393,-1.008757,-1.213680,-1.167155,-0.533149,1.019572,-0.524101,-0.697480,-0.32407,-0.538623,...

In [16]:
ROC_time = {'ROC_AUC': [], 'Time': [], 'n_estimators': [10, 20, 30]}
for estimators in [10, 20, 30]:
    start_time = datetime.datetime.now()

    result = 0
    kf = KFold(len(labels), n_folds=5, random_state=1, shuffle=True)
    for train_index, test_index in kf:
        X_train, X_test = np.array(data.iloc[train_index, :]), np.array(data.iloc[test_index, :])
        y_train, y_test = np.array(labels[train_index]), np.array(labels[test_index])   
        GB = GradientBoostingClassifier(n_estimators=estimators, verbose=True, random_state=1)
        GB.fit(X_train, y_train)
        y_pred = GB.predict_proba(X_test)[: ,1]
        result += roc_auc_score(y_test, y_pred)
    result = result / 5.     

    ROC_time['ROC_AUC'].append(result)
    ROC_time['Time'].append(datetime.datetime.now() - start_time)
    #print result    
    #print 'Time elapsed:', datetime.datetime.now() - start_time
ROC_time = DataFrame(ROC_time)
    
display(ROC_time)

      Iter       Train Loss   Remaining Time
         1           1.3785           11.09s
         2           1.3731           10.18s
         3           1.3683            9.17s
         4           1.3631            7.99s
         5           1.3583            6.57s
         6           1.3541            5.19s
         7           1.3497            3.90s
         8           1.3456            2.60s
         9           1.3417            1.29s
        10           1.3379            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3787           12.67s
         2           1.3734           10.61s
         3           1.3687            9.03s
         4           1.3638            7.57s
         5           1.3593            6.45s
         6           1.3545            5.19s
         7           1.3502            3.90s
         8           1.3466            2.58s
         9           1.3425            1.26s
        10           1.3386            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3790           10.29s
         2           1.3736            9.03s
         3           1.3688            7.84s
         4           1.3641            6.75s
         5           1.3591            5.58s
         6           1.3544            4.45s
         7           1.3505            3.38s
         8           1.3462            2.25s
         9           1.3421            1.12s
        10           1.3381            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3786            9.75s
         2           1.3733            8.82s
         3           1.3684            7.73s
         4           1.3638            6.65s
         5           1.3590            5.51s
         6           1.3542            4.52s
         7           1.3496            3.41s
         8           1.3453            2.32s
         9           1.3412            1.16s
        10           1.3375            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3788           12.60s
         2           1.3734           11.00s
         3           1.3687            9.72s
         4           1.3636            8.20s
         5           1.3588            6.68s
         6           1.3541            5.38s
         7           1.3498            3.97s
         8           1.3454            2.65s
         9           1.3418            1.32s
        10           1.3380            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3785           24.76s
         2           1.3731           23.81s
         3           1.3683           23.55s
         4           1.3631           22.17s
         5           1.3583           20.27s
         6           1.3541           18.72s
         7           1.3497           16.98s
         8           1.3456           15.43s
         9           1.3417           13.97s
        10           1.3379           12.59s
        20           1.3084            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3787           23.89s
         2           1.3734           21.74s
         3           1.3687           20.22s
         4           1.3638           18.77s
         5           1.3593           17.67s
         6           1.3545           16.36s
         7           1.3502           15.08s
         8           1.3466           13.96s
         9           1.3425           12.72s
        10           1.3386           11.54s
        20           1.3090            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3790           26.42s
         2           1.3736           23.79s
         3           1.3688           22.11s
         4           1.3641           20.47s
         5           1.3591           18.93s
         6           1.3544           17.30s
         7           1.3505           16.44s
         8           1.3462           15.14s
         9           1.3421           13.79s
        10           1.3381           12.61s
        20           1.3081            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3786           22.91s
         2           1.3733           21.95s
         3           1.3684           20.56s
         4           1.3638           19.58s
         5           1.3590           18.08s
         6           1.3542           16.62s
         7           1.3496           15.22s
         8           1.3453           14.00s
         9           1.3412           12.89s
        10           1.3375           11.77s
        20           1.3073            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3788           21.72s
         2           1.3734           20.51s
         3           1.3687           19.62s
         4           1.3636           18.43s
         5           1.3588           17.20s
         6           1.3541           16.13s
         7           1.3498           14.99s
         8           1.3454           13.79s
         9           1.3418           12.65s
        10           1.3380           11.44s
        20           1.3082            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3785           34.35s
         2           1.3731           33.07s
         3           1.3683           31.83s
         4           1.3631           30.69s
         5           1.3583           29.94s
         6           1.3541           28.89s
         7           1.3497           27.47s
         8           1.3456           26.11s
         9           1.3417           24.73s
        10           1.3379           23.67s
        20           1.3084           12.08s
        30           1.2880            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3787           34.19s
         2           1.3734           33.24s
         3           1.3687           32.29s
         4           1.3638           31.03s
         5           1.3593           29.97s
         6           1.3545           28.42s
         7           1.3502           27.70s
         8           1.3466           26.69s
         9           1.3425           26.00s
        10           1.3386           24.68s
        20           1.3090           12.18s
        30           1.2887            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3790           36.68s
         2           1.3736           35.19s
         3           1.3688           32.94s
         4           1.3641           31.32s
         5           1.3591           30.37s
         6           1.3544           29.81s
         7           1.3505           28.86s
         8           1.3462           27.33s
         9           1.3421           25.80s
        10           1.3381           24.33s
        20           1.3081           11.65s
        30           1.2880            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3786           38.81s
         2           1.3733           35.75s
         3           1.3684           34.67s
         4           1.3638           32.50s
         5           1.3590           31.83s
         6           1.3542           31.56s
         7           1.3496           30.53s
         8           1.3453           29.64s
         9           1.3412           28.52s
        10           1.3375           27.40s
        20           1.3073           14.19s
        30           1.2864            0.00s
      Iter       Train Loss   Remaining Time
         1           1.3788           45.73s
         2           1.3734           43.69s
         3           1.3687           42.57s
         4           1.3636           40.31s
         5           1.3588           38.29s
         6           1.3541           36.30s
         7           1.3498           33.56s
         8           1.3454           31.12s
         9           1.3418           29.67s
        10           1.3380           27.97s
        20           1.3082           12.81s
        30           1.2878            0.00s

    ROC_AUC            Time  n_estimators
0  0.666886 00:01:02.319036            10
1  0.682802 00:01:58.665624            20
2  0.689894 00:03:07.106621            30

[3 rows x 3 columns]

In [45]:
features = pandas.read_csv('/home/ubuntu/Desktop/Coursera ML/week7/final project/features.csv')
features = features.iloc[:, 2:]

NA_features = {'Features': [], 'NAs, %': []}
filled_values = dict(features.count())
for feature in filled_values.keys():
    if filled_values[feature] != len(features):
        NA_features['Features'].append(feature)
        NA_features['NAs, %'].append((len(features) - filled_values[feature]) / float(len(features)))
NA_features = DataFrame(NA_features)

features.fillna(value=0,inplace=True)

cols_del = ['duration',
            'radiant_win',
            'tower_status_radiant',
            'tower_status_dire',
            'barracks_status_radiant', 
            'barracks_status_dire']
data = features.drop(cols_del, axis=1)
labels = features['radiant_win']



from sklearn.preprocessing import StandardScaler
data = data.astype(float)
data = StandardScaler().fit_transform(data)
display(data)

ROC_time = {'ROC_AUC': [], 'Time': [], 'C': [0.0001, 0.001, 0.1, 1, 10, 100, 10000]}
for reg in [0.0001, 0.001, 0.1, 1, 10, 100, 10000]:
    start_time = datetime.datetime.now()
    
    result = 0
    kf = KFold(len(labels), n_folds=5, random_state=1, shuffle=True)
    for train_index, test_index in kf:
        X_train, X_test = np.array(data[train_index, :]), np.array(data[test_index, :])
        y_train, y_test = np.array(labels[train_index]), np.array(labels[test_index])   
        logist = LogisticRegression(C=reg, n_jobs=-1, random_state=1)
        logist.fit(X_train, y_train)
        y_pred = logist.predict_proba(X_test)[: ,1]
        result += roc_auc_score(y_test, y_pred)
    result = result / 5.     
    
    print result
    
    ROC_time['ROC_AUC'].append(result)
    ROC_time['Time'].append(datetime.datetime.now() - start_time)
    #print result    
    #print 'Time elapsed:', datetime.datetime.now() - start_time
ROC_time = DataFrame(ROC_time)
    
display(ROC_time)

array([[ 1.54068827, -1.24422828,  1.40080818, ..., -0.55115386,
         1.84600409, -1.12149424],
       [-0.92779756, -0.29225805,  0.50131354, ...,  0.67817009,
         0.43778816,  0.04394713],
       [ 1.54068827, -0.5686365 ,  0.50131354, ...,  0.67817009,
         0.43778816,  0.49028637],
       ...,
       [-0.57515673,  1.42743012,  0.50131354, ...,  0.67817009,
         0.43778816, -0.20401912],
       [-0.57515673,  1.48884755, -0.39818111, ...,  0.67817009,
         0.43778816, -0.87352799],
       [ 1.54068827, -0.04658831, -0.39818111, ..., -0.55115386,
        -0.97042777, -0.79913812]])

0.711203264538
0.716123312234
0.716273878443
0.716270200623
0.716269525784
0.716269506699
0.716269466449

            C   ROC_AUC            Time
0      0.0001  0.711203 00:00:06.177126
1      0.0010  0.716123 00:00:09.243221
2      0.1000  0.716274 00:00:13.667261
3      1.0000  0.716270 00:00:13.625925
4     10.0000  0.716270 00:00:14.152871
5    100.0000  0.716270 00:00:14.411017
6  10000.0000  0.716269 00:00:14.413192

[7 rows x 3 columns]

In [22]:
 	C 	ROC_AUC 	Time
0 	0.0001 	0.711203 	00:00:05.962271
1 	0.0010 	0.716123 	00:00:08.847996
2 	0.1000 	0.716274 	00:00:14.018855
3 	1.0000 	0.716270 	00:00:13.823342
4 	10.0000 	0.716270 	00:00:14.822234
5 	100.0000 	0.716270 	00:00:14.744653
6 	10000.0000 	0.716269 	00:00:15.044733

111